# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ece088fb8d0e1e124d0de01e1abb5b39661bb0dd4599858af425534e32348c80cfa3f17aef36a5a87e2a49936ce513dd5eeccbec431da88292c4fcdc3bd485

test:
  secret_key_base: 9f4095d7c81091307525a6dc0a0c44bd42c56643d5097cf19dafe00c81389ead107a4bcfce8c06d520c1ccede3f3aa829f5abada958f9dbbde5027ed0809be6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
